version: '3'
services:
  db:
    image: postgres:9.5.7-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=hello
      - POSTGRES_DB=sonar
  sonar:
    image: sonarqube:alpine
    depends_on:
      - db
    ports:
      - "32769:9000"
    environment:
      - SONARQUBE_JDBC_USERNAME=postgres
      - SONARQUBE_JDBC_PASSWORD=hello
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db/sonar
