version: '2.1'
services:
  server:
    image: gocd/gocd-server:v17.5.0
    ports:
      - "8154:8154"
      - "8153:8153"
  agent:
    image: gocd/gocd-agent-alpine-3.5:v17.5.0
    depends_on:
      - server
    environment:
      - GO_SERVER_URL=https://172.19.0.2:8154/go
