version: '2'
services:
  server:
    image: gocd/gocd-server:v17.5.0
    ports:
      - "8154:8154"
      - "8153:8153"
  agent:
    image: gocd/gocd-agent-alpine-3.5:v17.5.0
    depends_on:
      - server
    ports:
      - "8154:8154"
      - "8153:8153"
